name: functional-tests-arm
on: [push, pull_request]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt install -y git gcc
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
      - run: go version
      - run: date
      - name: Run functional
        run: |
          GO_BUILD_FLAGS='-v -mod=readonly' GOARCH=arm64  ./build && GOARCH=arm64 PASSES='functional' ./test



          https://go.dev/dl/go1.20.2.linux-amd64.tar.gz