name: Linux ARM64 
on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo amazon-linux-extras install epel
          sudo yum install -y git gcc ShellCheck
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.10"
      - run: go version
      - run: date
      - name: Run tests
        run: TEST_OPTS="PASSES='fmt bom dep build unit integration_e2e'" make test
