name: Tests-arm
on: [push, pull_request]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt install -y git gcc
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.15"
      - run: go version
      - run: date
      - name: Run tests
        run: |
          GOARCH=arm64 PASSES='fmt bom dep' ./test.sh
          GOARCH=arm64 CPU=1 PASSES='integration' RACE='false' ./test.sh
          GOARCH=arm64 CPU=2 PASSES='integration' RACE='false' ./test.sh
          GOARCH=arm64 CPU=4 PASSES='integration' RACE='false' ./test.sh
          GOARCH=arm64 PASSES='unit' RACE='true' CPU='4' ./test.sh -p=2
          GOARCH=arm64 PASSES='build' ./test.sh
          GO_BUILD_FLAGS='-v -mod=readonly' GOARCH=arm64 ./build.sh
